# ================================================================
# Legend, README and claim-trace text for the behavior main figure
# MMMSociability
# ================================================================
# Text only. Mirrors the role of Functions/gamm_manuscript_docs.R for the
# behavior figure, but every scientific number is PASSED IN rather than written
# as a literal, so a legend can never drift away from the table it describes.
# `facts` is the single list the assembler builds from the canonical tables; if a
# required entry is absent the writer fails rather than emitting a plausible
# sentence.
# ================================================================

.bmf_need <- function(facts, keys) {
  missing <- keys[!keys %in% names(facts)]
  if (length(missing) > 0L) {
    stop("behavior_main_figure_docs.R: missing required fact(s): ",
         paste(missing, collapse = ", "), call. = FALSE)
  }
  invisible(TRUE)
}

#' Draft figure legend for the behavior main figure.
#'
#' Deliberately states the temporal order first: the single most common
#' misreading of this figure would be to treat the CON/RES/SUS labels as if they
#' had been known when the RFID measurement was taken.
bmf_write_legend_draft <- function(path, facts) {
  .bmf_need(facts, c(
    "n_total", "n_female", "n_male", "group_counts", "combz_components_plain",
    "window_definition", "n_complete_window", "movement_unit",
    "assoc_rho", "assoc_ci", "assoc_q", "pred_r2", "pred_perm_p",
    "pred_n_perm", "pred_null_median", "pred_null_interval",
    "pred_repeated_r2", "pred_repeated_interval", "pred_interval_type",
    "pred_baseline_r2", "cv_scheme", "validation_scheme",
    "panel_a_domains", "pred_n_null_draws", "combz_parity_max_diff",
    "combz_thresholds", "combz_n_components"))

  gc <- facts$group_counts
  lines <- c(
    "# Behavior main figure - legend draft",
    "",
    paste("Generated by `Analysis/27_build_behavior_main_figure.R`.",
          "Four panels. Semantic filenames only; the manuscript figure number",
          "is assigned during whole-manuscript assembly."),
    "",
    "---",
    "",
    "## Full legend (draft)",
    "",
    # LENGTH IS A CONSTRAINT, NOT AN AFTERTHOUGHT. A Nature-style legend runs
    # to a few hundred words. The earlier draft ran past 800 because it also
    # carried provenance machinery (parity residuals, thresholds, coverage
    # tallies, the repeated-CV companion, the rank-model rationale). All of
    # that is preserved - in docs/COMBZ_CANONICAL_DEFINITION.md, the claim
    # trace, the key-results table and the Methods - so the legend can state
    # what the reader needs to read the figure and stop there. The "Wording
    # that must not be changed" section below is internal guidance and is not
    # part of the legend.
    paste0(
      "**Early home-cage locomotor activity carries internal out-of-sample ",
      "information about the later composite stress-burden score.** RFID ",
      "home-cage measurement precedes the endpoint battery: CON/RES/SUS ",
      "labels are derived from the later outcome and did not exist at the ",
      "time of recording, so they are called the later outcome group. ",
      "n = ", facts$n_total, " animals (", gc[["CON"]], " CON, ",
      gc[["RES"]], " RES, ", gc[["SUS"]], " SUS; ", facts$n_female,
      " female, ", facts$n_male, " male)."),
    "",
    paste0(
      "**(a) Experimental design and later outcome.** Chronology, left to ",
      "right: adolescent social instability stress; continuous RFID home-cage ",
      "monitoring across four repeated regroupings (CC1-CC4), from which the ",
      "analysed window and the domain inventory are drawn; then the later ",
      "behavioural and physiological battery. The listed domains are what the ",
      "continuous record characterises; none is presented as a group ",
      "difference. The later composite stress-burden score (CombZ) ",
      "is the unweighted mean of ", facts$combz_n_components, " standardized, ",
      "direction-aligned components (",
      paste(facts$combz_components_plain, collapse = ", "),
      "), so it is behavioural *and* physiological. LOWER CombZ = GREATER ",
      "later stress burden. Susceptibility is assigned within sex among ",
      "stress-exposed animals, strictly after the battery."),
    "",
    paste0(
      # window_definition already opens with "fixed clock window:", so do not
      # prefix another "Window:" here - it stutters and costs a word.
      "**(b) First-night Movement**, by later outcome group. ",
      sub("^fixed clock window: ", "Fixed clock window: ",
          facts$window_definition),
      ". Movement is ", facts$movement_unit,
      ". One point = one animal; bar = interquartile range, tick = median. ",
      "Descriptive only: no categorical contrast is annotated or claimed; the ",
      "panel shows the distribution of the variable analysed in (c) and (d)."),
    "",
    paste0(
      "**(c) Early Movement and later CombZ.** One point = one animal, pooled ",
      "across sex. A single pooled Spearman rank correlation with a bootstrap ",
      "95% confidence interval: rho = ", facts$assoc_rho, ", 95% CI ",
      facts$assoc_ci, ", Benjamini-Hochberg q = ", facts$assoc_q,
      " within the three-feature a priori family, n = ", facts$n_total,
      ". Group colour and shape are a visual aid; three within-group ",
      "correlations are not implied. No line is fitted: the canonical model ",
      "is rank-based. The negative sign means greater ",
      "early Movement goes with lower CombZ, i.e. greater later stress ",
      "burden. First-night Movement was associated with later CombZ."),
    "",
    paste0(
      "**(d) Out-of-sample prediction of later CombZ.** Left, observed against ",
      "leave-one-animal-out predicted CombZ; each point is one held-out ",
      "animal, predicted by a model refitted without it; the dashed line is ",
      "the identity y = x, for reference only. Right, ",
      facts$pred_n_null_draws, " permutation cross-validation R-squared ",
      "values, each produced by reshuffling the continuous CombZ endpoint and ",
      "re-running the entire leave-one-animal-out loop; null median dashed, ",
      "observed solid. ",
      "Cross-validated R-squared = ", facts$pred_r2, "; permutation p = ",
      facts$pred_perm_p, ". First-night Movement contained internal ",
      "out-of-sample predictive information about later CombZ. This is ",
      "internal validation within a single cohort, not external validation ",
      "and not an independent cohort, and no causal claim is made."),
    "",
    "---",
    "",
    "## Wording that must not be changed",
    "",
    paste0("- The cross-validation grouping unit is the **animal**. Cage, ",
           "social group and batch are not grouping units; do not imply ",
           "cage- or batch-level generalisation."),
    paste0("- 'Internal out-of-sample validation.' Never 'external ",
           "validation', 'independent cohort' or 'independently validated'. ",
           "The endpoint is continuous CombZ, so never report an AUC or ",
           "describe this as classification."),
    paste0("- The repeated-CV interval is a split-to-split resampling ",
           "interval. Do not call it a bootstrap or a confidence interval."),
    paste0("- The permutation null in (d) is the ACTUAL set of ",
           facts$pred_n_null_draws, " refit statistics persisted by the ",
           "producing stage. It must never be replaced by a density ",
           "reconstructed from published quantiles."),
    paste0("- **LOWER CombZ = greater later stress burden.** Do not describe ",
           "CombZ as a burden score without inverting the sign."),
    paste0("- Panel (a) is a design and definition schematic. Its domain ",
           "inventory states what is measured; it asserts no group difference ",
           "and must not be described as a multi-domain signature."),
    paste0("- Panel (b) is descriptive. Do not add stars, brackets, or q ",
           "values to it."),
    paste0("- Panel (c) reports ONE pooled correlation. Do not describe the ",
           "group colours as three correlations."),
    paste0("- CombZ provenance: canonical CombZ and outcome assignments are ",
           "reproduced exactly from the historically defined component ",
           "z-scores. Do not claim CombZ is fully regenerated from raw ",
           "behavioural and physiological data."),
    paste0("- Movement RMSSD is a supporting association only and must not be ",
           "described as an independent predictor. Entropy persistence (ACF1) ",
           "is not FDR-supported at the primary resolution and must carry ",
           "qualified wording."),
    "",
    "## Methods pointers",
    "",
    paste0("Panels (b)-(d) share one window and one animal set. Full ",
           "statistics are in `tables/manuscript/behavior_main_key_results.csv`; ",
           "per-panel plotted values are in `source_data/`; provenance is in ",
           "`manifests/`; claim-to-analysis mapping is in ",
           "`audit/behavior_main_claim_trace.csv`. Domain-contrast heatmaps, ",
           "the longitudinal movement characterisation, and the GAMM temporal ",
           "analyses are Extended Data."))
  writeLines(lines, path)
  invisible(path)
}


#' Co-author facing README for the Stage 27 output tree.
bmf_write_readme <- function(path, facts, registry_df, colours) {
  .bmf_need(facts, c("n_total", "window_definition", "validation_scheme"))
  lines <- c(
    "# Stage 27 - behavior main figure assembly",
    "",
    paste("ASSEMBLY ONLY. No model is fitted here, no p-value or q-value is",
          "computed or adjusted, no interval is estimated, no multiplicity",
          "family is redefined, and no scientific number is changed. Every",
          "value in every figure and table below is carried through from a",
          "frozen upstream canonical table."),
    "",
    "## What this stage may and may not do",
    "",
    "| May | May not |",
    "|---|---|",
    "| read canonical outputs | fit any model |",
    "| validate input schemas | recompute CombZ or redefine RES/SUS |",
    "| select manuscript-facing rows | reselect the first-night window |",
    "| format and relabel units | adjust p-values or define a family |",
    "| summarise the points it plots (median, quartiles, counts) | estimate a confidence interval |",
    "| export figures, source data, legends, manifests | recompute cross-validation |",
    "",
    paste("The prohibition is enforced from outside the script by",
          "`Testing/tests/test_behavior_main_figure_contracts.R`, which scans",
          "this stage's source for banned calls, mirroring the Stage 26",
          "precedent."),
    "",
    "## Directory layout",
    "",
    "```",
    "figures/main/                    the assembled main figure",
    "figures/panel_candidates/        individual panels and alternates",
    "figures/extended_data_candidates/ breadth/alternative panels",
    "figures/previews/                low-cost PNG previews",
    "tables/manuscript/               key results, human readable",
    "source_data/                     one file per panel + manifest",
    "legends/                         legend draft",
    "audit/                           claim trace, build record",
    "manifests/                       figure and input provenance",
    "```",
    "",
    paste("The tree is deliberately NOT resolution-scoped: a manuscript figure",
          "is not 'a 10-min analysis'. The resolution of each contributing",
          "source is recorded per input in",
          "`manifests/behavior_main_figure_input_manifest.csv` instead."),
    "",
    "## Presentation specification",
    "",
    paste0("Fixed identity colours, unchanged: CON `", colours[["CON"]],
           "`, RES `", colours[["RES"]], "`, SUS `", colours[["SUS"]], "`."),
    paste("Because RES is deliberately light, colour is never the only group",
          "encoding: point shape (circle / triangle / square) and line type",
          "(solid / long dash / dot-dash) carry the same information",
          "redundantly, which also keeps the figure readable in greyscale."),
    paste("Theme, palette, widths and export are the shared",
          "`Functions/mmm_publication_theme.R` and",
          "`Functions/gamm_publication_style_helpers.R`, so a stage figure and",
          "a manuscript figure can never disagree about group identity."),
    "Vector PDF + SVG with editable text, plus an optional PNG preview.",
    "",
    "## Reporting n",
    "",
    paste0("n = ", facts$n_total, " animals throughout panels (c) to (e). ",
           "Window: ", facts$window_definition, ". Validation scheme: ",
           facts$validation_scheme, "."),
    "",
    "## Inputs, by semantic key",
    "",
    paste("Resolved through `Functions/project_paths.R`. Moving any producer",
          "means editing that registry, not this stage."),
    "",
    "| key | role | stage | resolution |",
    "|---|---|---|---|",
    paste0("| `", registry_df$path_key, "` | ", registry_df$file_role, " | ",
           registry_df$producer_stage, " | ", registry_df$source_resolution,
           " |"),
    "",
    "## Known constraints carried from upstream",
    "",
    paste("- CombZ and the RES/SUS classification are now canonical",
          "in-repository (`Analysis/build_later_outcome_combz.R`) and are",
          "parity-gated against the upstream workbook. The one irreducible",
          "external dependency is the per-component z-scoring, which upstream",
          "is written as positional per-sex formula blocks. See",
          "`docs/COMBZ_CANONICAL_DEFINITION.md`."),
    paste("- The main figure has FOUR panels: a design/outcome framework, a",
          "descriptive first-night distribution, and two inferential panels.",
          "There is no main-figure slot for a domain heatmap and no",
          "configuration can create one. No multi-domain longitudinal overview",
          "is currently justifiable; the domain-contrast heatmaps and the",
          "longitudinal movement characterisation are Extended Data",
          "candidates. Decision: B3_NOT_JUSTIFIED__USE_FRAMEWORK_SCHEMATIC."),
    paste("- Panel a's domain inventory is a MEASUREMENT statement. Each row",
          "carries its own claim_status in the Source Data; the latent-state",
          "and inactivity rows are characterised only, and the inactive-phase",
          "biological reading is barred by KNOWN_LIMITATIONS item 3."),
    paste("- The categorical first-night group contrast has three",
          "implementations that disagree; the declared canonical one is null,",
          "so no categorical effect is annotated."),
    paste("- Panel E plots the actual persisted permutation draws, not a",
          "reconstruction from summary quantiles."),
    paste("- Validation is internal, not external.")
  )
  writeLines(lines, path)
  invisible(path)
}
