# ================================================================
# The analysis_ready output index
# MMMSociability
# ================================================================
# analysis_ready/output_index.csv maps every output group to its producer, manuscript role, status and runner. The
# definition lived in the legacy Stage 16 until 2026-10-05. Maintenance/Refresh-BehaviorOutputIndex.R writes the index
# from mmm_behavior_output_index() (and copies docs/BEHAVIOR_ANALYSIS_READY_DIRECTORY_README.md to
# analysis_ready/README.md), backing up the current files first. Analysis/STAGE_INVENTORY.csv lists the scripts;
# Testing/tests/test_behavior_output_index_source.R checks the index.
#
# Requires Functions/project_paths.R (mmm_behavior_output_index_entry(), MMM_NUMBERED_BEHAVIOR_ROOTS,
# mmm_source_relative_path(), mmm_behavior_numbered_source_root()) and the tibble package.
#
# legacy_path stays the provenance of the saved files. Once a numbered root is archived under its receipt, the note
# also names the retained original's current location, if that folder was present when the root moved.

#' The output index for one project root (a tibble, one row per output group).
mmm_behavior_output_index <- function(base_dir = mmm_project_root()) {
  output_group_index <- function(group) {
    mmm_behavior_output_index_entry(group, project_root = base_dir)
  }
  fn10 <- output_group_index("first_night_10min")
  behavior_metrics_foundation <- output_group_index("behavior_metrics_foundation")
  fn5 <- output_group_index("first_night_5min")
  spatial_tables <- output_group_index("spatial_tables")
  spatial_audit <- output_group_index("spatial_audit")
  spatial_models <- output_group_index("spatial_models")
  spatial_figures <- output_group_index("spatial_figures")
  dyadic_contacts <- output_group_index("dyadic_contacts")
  social_networks_5min <- output_group_index("social_networks_5min")
  gamm_features_10min <- output_group_index("gamm_features_10min")
  state_space_5min <- output_group_index("state_space_5min")
  hmm_states_10min <- output_group_index("hmm_states_10min")
  hmm_states_5min <- output_group_index("hmm_states_5min")
  temporal_instability_10sec <- output_group_index("temporal_instability_10sec")
  history_temporal_1min <- output_group_index("history_temporal_instability_1min")
  history_temporal_5min <- output_group_index("history_temporal_instability_5min")
  history_state_1min <- output_group_index("history_state_space_1min")
  history_state_10min <- output_group_index("history_state_space_10min")
  history_social_10sec <- output_group_index("history_social_networks_10sec")
  history_social_1min <- output_group_index("history_social_networks_1min")
  history_social_10min <- output_group_index("history_social_networks_10min")
  history_social_30min <- output_group_index("history_social_networks_30min")
  history_gamm_30min <- output_group_index("history_gamm_features_30min")
  adaptation_kinetics_10min <- output_group_index("adaptation_kinetics_10min")
  sleep_like_inactivity_10min <- output_group_index("sleep_like_inactivity_10min")
  phase_organization_10min <- output_group_index("phase_organization_10min")
  nonlinear_dynamics_5min <- output_group_index("nonlinear_dynamics_5min")
  systems_phenotyping_5min <- output_group_index("systems_phenotyping_5min")
  inactive_phase_qc_audit <- output_group_index("inactive_phase_qc_audit")
  rfid_domain_comparison_audit <- output_group_index("rfid_domain_comparison_audit")
  rfid_leading_bin_seed_audit <- output_group_index("rfid_leading_bin_seed_audit")
  rfid_construct_audit <- output_group_index("rfid_construct_audit")
  rfid_conservatism_audit <- output_group_index("rfid_conservatism_audit")
  rfid_alternative_inference_audit <- output_group_index("rfid_alternative_inference_audit")
  rfid_reliability_audit <- output_group_index("rfid_reliability_audit")
  systems_dashboard_5min <- output_group_index("systems_dashboard_5min")
  proteomics_mnn_primary <- output_group_index("proteomics_mnn_primary")
  proteomics_mnn_sensitivity <- output_group_index("proteomics_mnn_sensitivity")
  tracking_qc_history <- output_group_index("history_tracking_integrity_10sec")
  proteomics_inputs <- output_group_index("proteomics_module_scores")
  output_index <- tibble::tribble(
    ~stage, ~analysis, ~resolution, ~artifact_type, ~canonical_path, ~producer, ~manuscript_role, ~status, ~legacy_path, ~notes, ~runner_registration,
    "00", "QC tracking integrity", NA_character_, "manual diagnostic output group", NA_character_, "Analysis/00_qc_tracking_integrity.R", "technical QC", "legacy_pending_migration", "analysis_ready/00_qc_tracking_integrity/", "May 2026 historical optional QC snapshot; current Stage 01 lineage unverified. September 2026 pooled and 10-second diagnostic runs under quality_control/tracking_integrity/ are unpromoted and unsuitable for exclusions.", "manual diagnostic",
    "00-history", "Historical tracking-integrity QC snapshot", "10sec", "historical output group", tracking_qc_history$canonical_path, "Analysis/00_qc_tracking_integrity.R (May 2026 run)", "historical optional input", tracking_qc_history$status, tracking_qc_history$legacy_path, "Eight May 2026 files; the retired Stage 16 package and release builder read two of its tables. Current Stage 01 lineage unverified (113 animals against the canonical 111).", "manual historical",
    "01", "Multiscale behavior metrics", "multiple", "pipeline output group", behavior_metrics_foundation$canonical_path, "Analysis/01_build_multiscale_behavior_metrics.R", "canonical input layer", behavior_metrics_foundation$status, behavior_metrics_foundation$legacy_path, "Current Stage 01 metrics; separate identity-audit and spatial outputs retain distinct owners. 10min_based/all_behavior_metrics.csv is pinned by sha256 by the Stage 29 v1.0.1 release; the stage calls the frozen-input guard, which refuses a live rerun.", "run_all_analysis.R (profile heatmap_inputs; guarded)",
    "01-identity-history", "Historical cross-scale identity audit", "multiple", "historical audit output group", NA_character_, "Testing/audits/validate_cross_scale_animal_identity.R", "historical provenance", "historical_source_retained", "analysis_ready/03_derived_metrics/qc/", "Eight August cross_scale_identity_*.csv reports predate the current Stage 01 metrics; a future manual run writes under analyses/cross_scale_identity_validation/.", "manual historical",
    "02", "Dyadic RFID contacts", "10min contact bins", "pipeline output group", dyadic_contacts$canonical_path, "Analysis/02_build_dyadic_rfid_contacts.R", "secondary/social source", dyadic_contacts$status, dyadic_contacts$legacy_path, "Current Stage 02 output; cookie-habituation uses a separate explicit output override.", "run_all_analysis.R (profile legacy_systems)",
    "03", "Movement phase statistics", "10min", "pipeline output group", "analysis_ready/pipeline/03_movement_phase_stats/10min/", "Analysis/03_primary_raw_movement_phase_stats.R", "secondary manuscript evidence", "producer_migrated_legacy_artifacts_retained", "analysis_ready/03_primary_raw_movement_phase_stats/10min_based/", "Stage 16 reads canonical files only; the older divergent set remains for historical comparison.", "run_all_analysis.R (profile legacy_systems)",
    "04", "Temporal instability", "10sec", "pipeline output subgroup", temporal_instability_10sec$canonical_path, "Analysis/04_temporal_instability.R", "mechanistic/secondary", temporal_instability_10sec$status, temporal_instability_10sec$legacy_path, "Current Stage 04 branch; not included in Stage 16 primary reporting.", "run_all_analysis.R (profile legacy_systems)",
    "04-history", "Historical temporal-instability resolutions", "1min, 5min", "historical output group", NA_character_, "Historical temporal-instability runs", "historical provenance", "historical_source_retained", "analysis_ready/06_behavioral_dynamics/temporal_instability/", "Family overview; resolution rows below track receipt-selected history copies.", "manual historical",
    "04-history-1min", "Historical temporal instability", "1min", "historical output subgroup", history_temporal_1min$canonical_path, "Historical temporal-instability run", "historical optional input", history_temporal_1min$status, history_temporal_1min$legacy_path, "May run retained as historical input; a semantic copy does not refresh its scientific provenance.", "manual historical",
    "04-history-5min", "Historical temporal instability", "5min", "historical output subgroup", history_temporal_5min$canonical_path, "Historical temporal-instability run", "historical optional input", history_temporal_5min$status, history_temporal_5min$legacy_path, "Stage 15 may read this May run; a semantic copy does not validate its source choice.", "manual historical",
    "05", "Behavioral state space", "5min", "pipeline output subgroup", state_space_5min$canonical_path, "Analysis/05_behavioral_state_space.R", "exploratory/mechanistic", state_space_5min$status, state_space_5min$legacy_path, "Current Stage 05 writer; not promoted into Stage 16.", "run_all_analysis.R (profile legacy_systems)",
    "05-history", "Historical state-space resolutions", "1min, 10min", "historical output group", NA_character_, "Historical state-space runs", "historical provenance", "historical_source_retained", "analysis_ready/06_behavioral_dynamics/state_space/", "Family overview; resolution rows below track receipt-selected history copies.", "manual historical",
    "05-history-1min", "Historical behavioral state space", "1min", "historical output subgroup", history_state_1min$canonical_path, "Historical state-space run", "historical provenance", history_state_1min$status, history_state_1min$legacy_path, "May run retained for Stage 10 and optional readers; no current-producer claim.", "manual historical",
    "05-history-10min", "Historical behavioral state space", "10min", "historical output subgroup", history_state_10min$canonical_path, "Historical state-space run", "historical provenance", history_state_10min$status, history_state_10min$legacy_path, "May run retained for Stage 10 and optional readers; no current-producer claim.", "manual historical",
    "06", "Dynamic social networks", "5min", "pipeline output subgroup", social_networks_5min$canonical_path, "Analysis/06_dynamic_social_networks.R", "secondary/social", social_networks_5min$status, social_networks_5min$legacy_path, "Current Stage 06 writer; not included without a selected manuscript result.", "run_all_analysis.R (profile legacy_systems)",
    "06-history", "Historical social-network resolutions", "10sec, 1min, 10min, 30min", "historical output group", NA_character_, "Historical network runs", "historical provenance", "historical_source_retained", "analysis_ready/06_behavioral_dynamics/social_networks/", "Family overview; resolution rows below track receipt-selected history copies.", "manual historical",
    "06-history-10sec", "Historical dynamic social networks", "10sec", "historical output subgroup", history_social_10sec$canonical_path, "Historical social-network run", "historical provenance", history_social_10sec$status, history_social_10sec$legacy_path, "May run retained for Stage 10 and optional readers; separate from the current five-minute producer.", "manual historical",
    "06-history-1min", "Historical dynamic social networks", "1min", "historical output subgroup", history_social_1min$canonical_path, "Historical social-network run", "historical provenance", history_social_1min$status, history_social_1min$legacy_path, "May run retained for Stage 10 and optional readers; separate from the current five-minute producer.", "manual historical",
    "06-history-10min", "Historical dynamic social networks", "10min", "historical output subgroup", history_social_10min$canonical_path, "Historical social-network run", "historical provenance", history_social_10min$status, history_social_10min$legacy_path, "May run retained for Stage 10 and optional readers; separate from the current five-minute producer.", "manual historical",
    "06-history-30min", "Historical dynamic social networks", "30min", "historical output subgroup", history_social_30min$canonical_path, "Historical social-network run", "historical provenance", history_social_30min$status, history_social_30min$legacy_path, "May run retained for Stage 10 and optional readers; separate from the current five-minute producer.", "manual historical",
    "07", "GAMM trajectory features", "10min", "pipeline output subgroup", gamm_features_10min$canonical_path, "Analysis/07_gamm_trajectory_features.R", "mechanistic/secondary", gamm_features_10min$status, gamm_features_10min$legacy_path, "Current Stage 07 writer; not promoted into Stage 16.", "run_all_analysis.R (profile legacy_systems)",
    "07-history", "Historical GAMM trajectory features", "30min", "historical output group", NA_character_, "Historical trajectory run", "historical optional input", "historical_source_retained", "analysis_ready/06_behavioral_dynamics/gamm_features/30min_based/", "Family overview; the resolution row below tracks the receipt-selected history copy.", "manual historical",
    "07-history-30min", "Historical GAMM trajectory features", "30min", "historical output subgroup", history_gamm_30min$canonical_path, "Historical GAMM run", "historical optional input", history_gamm_30min$status, history_gamm_30min$legacy_path, "Stage 15 reads this May run separately from the current ten-minute producer.", "manual historical",
    "08", "HMM states", "10min primary", "pipeline output subgroup", hmm_states_10min$canonical_path, "Analysis/08_hmm_behavioral_states_optional.R", "systems dashboard input", hmm_states_10min$status, hmm_states_10min$legacy_path, "Required by Stage 14 (the file name still says optional for historical reasons); latent-state architecture is not primary evidence.", "run_all_analysis.R (profile heatmap_inputs)",
    "08-5min", "HMM states sensitivity", "5min sensitivity", "pipeline output subgroup", hmm_states_5min$canonical_path, "Analysis/08_hmm_behavioral_states_optional.R", "sensitivity", hmm_states_5min$status, hmm_states_5min$legacy_path, "Secondary HMM resolution; does not replace the declared 10-minute primary.", "run_all_analysis.R (profile heatmap_inputs)",
    "08-audit-current", "HMM gap-aware revalidation", "10min primary; 5min sensitivity", "manual audit output group", "analysis_ready/analyses/hmm_revalidation_runs/current_stage08_review_20260924/", "Testing/audits/audit_step6_longitudinal_gapaware_robustness.R; Testing/audits/audit_hmm_cross_optimum_gapaware.R", "scientific review only", "current_revalidation_unpromoted", "analysis_ready/12_systems_neuroscience_summary/5min_based/audit_hmm_state_architecture/", "Five current-input tables; the source registry now cites this run with conditional or excluded statuses. Manuscript and release products were not refreshed.", "manual audit",
    "08-audit-history", "Historical HMM architecture audits", "mixed", "historical output group", NA_character_, "Testing/audits/audit_hmm_state_architecture_*.R; Testing/audits/audit_first_night_*.R", "historical provenance", "historical_source_retained", "analysis_ready/12_systems_neuroscience_summary/5min_based/audit_hmm_state_architecture/", "183 files dated September 2-4 2026; inputs predate the current Stage 01 and Stage 08 runs. Audit reruns now require separate fresh replay folders; this string records the saved original layout.", "manual historical",
    "09", "Early prediction", "10min", "pipeline output group", "analysis_ready/pipeline/09_early_prediction/10min/", "Analysis/09_early_prediction_model_ladder.R", "frozen-lineage input (treated as registered)", "canonical_only_legacy_path_absent", "analysis_ready/06_behavioral_dynamics/early_prediction_model_ladder/10min_based/", "Its tables/model_ladder_input.csv is pinned by sha256 by the Stage 29 v1.0.1 release and Stage 32; the runner's frozen-input guard refuses a live rerun. The manuscript reads these results through the frozen bundle ebb_v101.", "run_all_analysis.R (profile early_prediction; guarded)",
    "10", "Systems prediction", "10min", "pipeline output group", "analysis_ready/pipeline/10_systems_prediction/10min/", "Analysis/10_systems_feature_prediction_ladder.R", "exploratory systems extension", "producer_migrated_legacy_artifacts_retained", NA_character_, "Current writer uses pipeline/10_systems_prediction. Historical self-ingested outputs are archived and forbidden as input; the systems extension is not primary manuscript evidence.", "run_all_analysis.R (profile legacy_systems; RUN_SYSTEMS_EXTENSION, default TRUE)",
    "11", "Adaptation kinetics", "10min", "pipeline output subgroup", adaptation_kinetics_10min$canonical_path, "Analysis/11_behavioral_adaptation_kinetics.R", "mechanistic/secondary", adaptation_kinetics_10min$status, adaptation_kinetics_10min$legacy_path, "Current Stage 11 output; not included without a selected manuscript result.", "run_all_analysis.R (profile legacy_systems)",
    "11-history", "Historical adaptation kinetics", "5min", "historical output group", NA_character_, "Historical adaptation run", "historical optional input", "historical_source_retained", "analysis_ready/15_behavioral_adaptation_kinetics/5min_based/", "Older five-minute branch is retained; future Stage 15 runs select the declared ten-minute producer output.", "manual historical",
    "12", "Sleep-like quiescence", "10min", "pipeline output subgroup", sleep_like_inactivity_10min$canonical_path, "Analysis/12_sleep_like_quiescence_metrics.R", "secondary", sleep_like_inactivity_10min$status, sleep_like_inactivity_10min$legacy_path, "Current Stage 12 output; not EEG-validated or included in current Stage 16.", "run_all_analysis.R (profile heatmap_inputs)",
    "12-history", "Historical sleep-like inactivity", "5min", "historical output group", NA_character_, "Historical quiescence run", "historical optional input", "historical_source_retained", "analysis_ready/16_sleep_like_inactivity_metrics/5min_based/", "Older five-minute branch is retained; future Stage 15 runs select the declared ten-minute producer output.", "manual historical",
    "13", "Phase organization", "10min", "pipeline output subgroup", phase_organization_10min$canonical_path, "Analysis/13_ethological_phase_organization.R", "mechanistic/secondary", phase_organization_10min$status, phase_organization_10min$legacy_path, "Current Stage 13 output; not included without a selected manuscript result.", "run_all_analysis.R (profile legacy_systems)",
    "13-history", "Historical phase organization", "5min", "historical output group", NA_character_, "Historical phase-organization run", "historical optional input", "historical_source_retained", "analysis_ready/17_ethological_phase_organization/5min_based/", "Older five-minute branch is retained; future Stage 15 runs select the declared ten-minute producer output.", "manual historical",
    "14", "Systems summary and domain heatmaps", "5min", "pipeline output group", systems_dashboard_5min$canonical_path, "Analysis/14_systems_neuroscience_summary_dashboard.R", "exploratory systems layer; domain heatmaps", systems_dashboard_5min$status, systems_dashboard_5min$legacy_path, "Dashboard and domain-heatmap products; first-night and manual audit families have separate output groups. Rebuilt only in a guarded sandbox and promoted with a producer-rerun record (docs/behavior_output_producer_reruns/).", "run_all_analysis.R (profile heatmap_inputs); guarded sandbox and promotion",
    "14-first-night-10min", "First-night five-domain characterization", "10min primary", "pipeline output subgroup", fn10$canonical_path, "Functions/first_night_domain_driver.R via Analysis/14_systems_neuroscience_summary_dashboard.R", "secondary first-night source and extended-data candidate", fn10$status, fn10$legacy_path, "Ten primary files; separate from Stage 14 dashboard exports and Stage 28's four-domain analysis.", "via Stage 14 (guarded sandbox and promotion)",
    "14-first-night-5min", "First-night five-domain characterization", "5min sensitivity", "pipeline output subgroup", fn5$canonical_path, "Functions/first_night_domain_driver.R via Analysis/14_systems_neuroscience_summary_dashboard.R", "sensitivity", fn5$status, fn5$legacy_path, "Ten sensitivity files; this resolution cannot replace the declared 10-minute primary.", "via Stage 14 (guarded sandbox and promotion)",
    "14-inactive-qc-audit", "Inactive-phase QC redesign audit", NA_character_, "manual audit output group", inactive_phase_qc_audit$canonical_path, "Testing/audits/audit_inactive_phase_qc_redesign.R", "unpromoted QC proposal", inactive_phase_qc_audit$status, inactive_phase_qc_audit$legacy_path, "Three audit tables; the proposed rule has not been adopted in production.", "manual audit",
    "14-rfid-domain-comparison-audit", "Legacy and four-domain RFID comparison", "10min", "manual audit output group", rfid_domain_comparison_audit$canonical_path, "Testing/audits/audit_rfid_legacy_vs_new_domains.R", "supporting construct and inference audit", rfid_domain_comparison_audit$status, rfid_domain_comparison_audit$legacy_path, "Four comparison tables; reads activated first-night and local Stage 28 outputs. No manuscript claim is promoted by this path change.", "manual audit",
    "14-rfid-leading-bin-seed-audit", "RFID leading-bin seed sensitivity", "10min", "manual audit output group", rfid_leading_bin_seed_audit$canonical_path, "Testing/audits/audit_rfid_leading_bin_seed_sensitivity.R", "supporting robustness audit", rfid_leading_bin_seed_audit$status, rfid_leading_bin_seed_audit$legacy_path, "Twelve audit tables; Stage 28 contract reads the burden-by-cage-change and burden-change-by-group tables. Primary analysis keeps the full window.", "manual audit",
    "14-rfid-construct-audit", "RFID phenotype-blind construct audit", "10min and 5min", "manual audit output group", rfid_construct_audit$canonical_path, "Testing/audits/audit_rfid_domain_construct_blind.R", "supporting construct audit", rfid_construct_audit$status, rfid_construct_audit$legacy_path, "Eleven audit tables; no formula or domain is changed automatically by this audit.", "manual audit",
    "14-rfid-conservatism-audit", "RFID conservatism diagnostic", "10min", "manual audit output group", rfid_conservatism_audit$canonical_path, "Testing/audits/audit_rfid_conservatism.R", "exploratory precision and power diagnostic", rfid_conservatism_audit$status, rfid_conservatism_audit$legacy_path, "Eleven audit tables; exploratory p-values do not select a primary analysis.", "manual audit",
    "14-rfid-alternative-inference-audit", "RFID alternative inference diagnostic", "10min", "manual audit output group", rfid_alternative_inference_audit$canonical_path, "Testing/audits/audit_rfid_alternative_inference.R", "exploratory inference diagnostic", rfid_alternative_inference_audit$status, rfid_alternative_inference_audit$legacy_path, "Ten audit tables; no Stage 28 decision changes from a path migration.", "manual audit",
    "14-rfid-reliability-audit", "RFID reliability and stability diagnostic", "10min", "manual audit output group", rfid_reliability_audit$canonical_path, "Testing/audits/audit_rfid_reliability_and_improvement.R", "diagnostic reliability audit", rfid_reliability_audit$status, rfid_reliability_audit$legacy_path, "Seven audit tables; cross-occasion stability is distinct from instrument reliability.", "manual audit",
    "15-primary", "Behavior-proteomics MNN primary", NA_character_, "pipeline output group", proteomics_mnn_primary$canonical_path, "Analysis/15_behavior_proteomics_integration.R", "exploratory cross-modal layer", proteomics_mnn_primary$status, proteomics_mnn_primary$legacy_path, "Historical integration includes HMM features in primary axes and unverified five-minute phase inputs; requires reviewed rerun. Full proteomics label is in proteomics_integration_output_dir_map.csv.", "run_all_analysis.R (profile legacy_systems; RUN_BEHAVIOR_PROTEOMICS, default FALSE)",
    "15-sensitivity", "Behavior-proteomics MNN sensitivity", NA_character_, "pipeline output group", proteomics_mnn_sensitivity$canonical_path, "Analysis/15_behavior_proteomics_integration.R", "exploratory cross-modal sensitivity", proteomics_mnn_sensitivity$status, proteomics_mnn_sensitivity$legacy_path, "Historical integration includes HMM features in primary axes and unverified five-minute phase inputs; requires reviewed rerun. Full proteomics label is in proteomics_integration_output_dir_map.csv.", "run_all_analysis.R (profile legacy_systems; RUN_BEHAVIOR_PROTEOMICS, default FALSE)",
    "15-inputs", "Proteomics module scores", NA_character_, "input layer", proteomics_inputs$canonical_path, "External proteomics module-score export (May 2026)", "Stage 15 input", proteomics_inputs$status, proteomics_inputs$legacy_path, "Two module-score tables read by Stage 15 and one earlier draft that no code reads; not regenerated here.", "external input",
    "16", "Manuscript behavior report (retired)", "10min", "retired output group", "analysis_ready/history/retired/manuscript_behavior/", "Analysis/16_manuscript_behavior_report.R", "retired legacy product", "retired_archived", "analysis_ready/16_manuscript_behavior_report/10min_based/", "Superseded by the frozen behaviour bundles (16b) and the manuscript repository's renderers. Its index and README writer is now Functions/behavior_output_index.R with Maintenance/Refresh-BehaviorOutputIndex.R.", "retired 2026-10-05 (the code is kept in git history)",
    "19-tables", "Spatial occupancy derived tables", NA_character_, "pipeline output subgroup", spatial_tables$canonical_path, "Analysis/19_spatial_occupancy_maps.R", "secondary/spatial", spatial_tables$status, spatial_tables$legacy_path, "Six result tables; selected tables also have publication_ready copies.", "manual",
    "19-audit", "Spatial occupancy audit and provenance", NA_character_, "pipeline output subgroup", spatial_audit$canonical_path, "Analysis/19_spatial_occupancy_maps.R", "supporting audit", spatial_audit$status, spatial_audit$legacy_path, "Eight QC and provenance files; the current layout shares the result-table directory.", "manual",
    "19-models", "Spatial occupancy models", NA_character_, "pipeline output group", spatial_models$canonical_path, "Analysis/19_spatial_occupancy_maps.R", "secondary/spatial", spatial_models$status, spatial_models$legacy_path, "Six model and contrast files; Stage 10 excludes this result tree from feature discovery.", "manual",
    "19-figures", "Spatial occupancy figures", NA_character_, "pipeline output group", spatial_figures$canonical_path, "Analysis/19_spatial_occupancy_maps.R", "secondary/spatial", spatial_figures$status, spatial_figures$legacy_path, "Five SVGs; separate copies are retained in publication_ready.", "manual",
    "support-13", "Nonlinear systems dynamics", "5min", "supporting pipeline output group", nonlinear_dynamics_5min$canonical_path, "Analysis/_supporting/13_nonlinear_systems_dynamics.R", "exploratory input to Stages 10, 14 and 15", nonlinear_dynamics_5min$status, nonlinear_dynamics_5min$legacy_path, "Manual supporting producer; original September run retained and not regenerated by run_all_analysis.R.", "manual supporting script",
    "support-14", "Next-generation behavioral phenotyping", "5min", "supporting pipeline output group", systems_phenotyping_5min$canonical_path, "Analysis/_supporting/14_nextgen_behavioral_phenotyping.R", "exploratory input to Stages 10 and 14", systems_phenotyping_5min$status, systems_phenotyping_5min$legacy_path, "Manual supporting producer; original September run retained and not regenerated by run_all_analysis.R.", "manual supporting script",
    "endpoint", "Later outcome composite (CombZ)", NA_character_, "canonical endpoint", "analysis_ready/canonical/later_outcome_combz/tables/", "Analysis/build_later_outcome_combz.R", "canonical outcome definition", "canonical", NA_character_, "Reproduces the upstream workbook endpoint exactly and hard-stops on parity failure. Cross-stage shared input, owned by no numbered stage. The animal-level table is pinned by sha256 (1f6a2a69) by the Stage 29, 30 and 32 runs, and the producer is pinned by its git blob (d850859e).", "manual",
    "20", "First active phase after CC1, within-night GAMM profile", "10min", "pipeline output group", "analysis_ready/pipeline/20_first_night_gamm/10min/", "Analysis/20_first_night_gamm.R", "Extended Data candidate (descriptive; no group inference)", "descriptive_candidate", NA_character_, "The within-night 10-min profile by sex and group, which no frozen analysis shows. Display trajectories only: its group contrasts are null, have no cage term (CON is 3 intact cages per sex) and were seen before the frozen analyses; inference stays with Stages 29 and 32. The 2026-09-07 leftovers are archived under history/retired/20_first_night_gamm_20260907/.", "manual",
    "21", "CC1 active nights 1-4 GAMM (retired)", "10min", "retired output group", "analysis_ready/history/retired/21_cc1_active_longitudinal_gamm/", "Analysis/21_cc1_active_longitudinal_gamm.R", "retired", "retired_archived", NA_character_, "All contrasts null; the male rise across nights is shared by CON and confounded with the cohort sets. Stage 32 gives the A1-A4 rates.", "retired 2026-10-05 (the code is kept in git history)",
    "22", "Active phase after each cage change, within-night GAMM profile", "10min", "pipeline output group", "analysis_ready/pipeline/22_repeated_cagechange_acute_gamm/10min/", "Analysis/22_repeated_cagechange_acute_gamm.R", "Extended Data candidate (descriptive; no group inference)", "descriptive_candidate", NA_character_, "Where in the night the CC1-to-CC4 change happens (mostly in the first hour after 18:30). Display trajectories only: the CC4-CC1 p-values ignore cohort variation and CON shares the change, so it is not adaptation (Stage 32 registry section 9); phenotype-dependent change is null. The 2026-09-07 leftovers are archived under history/retired/22_repeated_cagechange_acute_gamm_20260907/.", "manual",
    "23", "First light phase after CC1, Markov GAMM (retired)", "10min", "retired output group", "analysis_ready/history/retired/23_first_inactive_gamm/", "Analysis/23_first_inactive_gamm.R", "retired", "retired_archived", NA_character_, "Its SIS-vs-CON contrasts have no cage term and lose support once CON cages are the unit; the measure cannot be separated from detection loss (KNOWN_LIMITATIONS item 3). The frozen configuration already excludes it from products; the archive stays the record its disclosure refers to.", "retired 2026-10-05 (the code is kept in git history)",
    "24", "CC1 light-phase blocks, Markov GAMM (retired)", "10min", "retired output group", "analysis_ready/history/retired/24_cc1_inactive_longitudinal_gamm/", "Analysis/24_cc1_inactive_longitudinal_gamm.R", "retired", "retired_archived", NA_character_, "All contrasts null; same measure and limits as Stage 23.", "retired 2026-10-05 (the code is kept in git history)",
    "25", "First light phase after each cage change, Markov GAMM (retired)", "10min", "retired output group", "analysis_ready/history/retired/25_repeated_cagechange_inactive_gamm/", "Analysis/25_repeated_cagechange_inactive_gamm.R", "retired", "retired_archived", NA_character_, "No supported change; its CON-referenced contrasts lose support once CON cages are the unit. Frozen Stages 29, 30 and 32 cover the light phase.", "retired 2026-10-05 (the code is kept in git history)",
    "26", "GAMM manuscript assembly (retired)", "10min", "retired output group", "analysis_ready/history/retired/26_gamm_manuscript_outputs/", "Analysis/26_build_gamm_manuscript_outputs.R", "retired", "retired_archived", NA_character_, "Assembly only; nothing in the manuscript repositories reads it.", "retired 2026-10-05 (the code is kept in git history)",
    "27", "Behavior main figure (retired)", NA_character_, "retired output group", "analysis_ready/history/retired/27_behavior_main_figure/", "Analysis/27_build_behavior_main_figure.R; Analysis/27_candidate_recompose_behavior_main_figure.R", "retired legacy product", "retired_archived", NA_character_, "Superseded by the manuscript repository's Figure 1, rendered from ebb_v101.", "retired 2026-10-05 (the code is kept in git history)",
    "28", "RFID four-domain characterization", "10min primary; 5min sensitivity", "pipeline output group", "analysis_ready/pipeline/28_rfid_behavioral_domains/", "Analysis/28_rfid_behavioral_domains.R", "frozen-lineage input; secondary descriptive", "active_producer_pinned", NA_character_, "Committed producer. Its acute_window_* tables are pinned by sha256 by the Stage 29 v1.0.1 release; the stage calls the frozen-input guard, which refuses a live rerun.", "manual (guarded)",
    "16b", "Canonical behaviour bundle", NA_character_, "frozen export group", "analysis_ready/canonical/behavior_bundle/", "Analysis/16b_canonical_behavior_bundle.R", "manuscript-facing frozen export", "frozen", NA_character_, "One immutable folder per bundle, listed in BUNDLE_REGISTRY.csv; ebb_v101_20260929_b2ce507 is the export Exp9_manuscript imports and renders Figure 1 from.", "manual",
    "16c", "Figure support bundle", NA_character_, "frozen export group", "analysis_ready/canonical/figure_support_bundle/", "Analysis/16c_figure_support_bundle.R", "manuscript-facing frozen export", "frozen", NA_character_, "fsb_v1_20260930_f06552c and fsb_v2_20260930_a23d699; immutable, listed in BUNDLE_REGISTRY.csv.", "manual",
    "29", "Canonical behavioural characterisation releases", NA_character_, "registered run group", "analysis_ready/pipeline/29_canonical_behavior_releases/", "Analysis/29_canonical_behavior_characterization.R", "registered primary evidence", "frozen", NA_character_, "Run v101_dv2_b2ce507 (configuration v1.0.1, data version v2) is manuscript-facing; each run folder is written once behind identity gates (docs/STAGE29_RELEASE_v1.0.1_dv2.md).", "manual",
    "29b", "Post hoc CON/RES/SUS contrasts", NA_character_, "registered run group", "analysis_ready/pipeline/29b_posthoc_con_contrasts/", "Analysis/29b_posthoc_con_contrasts.R", "registered post hoc evidence", "frozen", NA_character_, "Run v1.0_7f1da1f, written once (docs/POSTHOC_CON_CONTRASTS_REGISTRY_v1.0.md).", "manual",
    "30", "Exploratory outcome screen", NA_character_, "registered run group", "analysis_ready/pipeline/30_exploratory_screen/", "Analysis/30_exploratory_screen.R", "registered exploratory screen", "frozen", NA_character_, "Run v1.0_be71e2f, run once and never re-run REAL (docs/stage30/STAGE30_REGISTRY_v1.0.md).", "manual",
    "30b", "Stage 30 figure bundle", NA_character_, "frozen export group", "analysis_ready/canonical/stage30_figure_bundle/", "Analysis/30b_stage30_figure_bundle.R", "manuscript-facing frozen export", "frozen", NA_character_, "s30b_v10_20260929_5394f2f; immutable, listed in BUNDLE_REGISTRY.csv.", "manual",
    "31", "CC4 grid-associated period", NA_character_, "run-id output group", "analysis_ready/analyses/cc4_grid_exposure/", "Analysis/31_cc4_grid_exposure.R; 31b, 31c and 31d", "descriptive and inferential CC4 candidates", "active_run_folders", NA_character_, "New run-id folders only; an existing folder is refused (docs/CC4_GRID_EXPOSURE.md, CC4_PHASE_STATISTICS.md, CC4_PHENOTYPE_STATISTICS.md).", "manual",
    "32", "SIS exposure, within-episode adaptation and early prediction beyond Batch", NA_character_, "registered run group", "analysis_ready/pipeline/32_behavior_exposure_adaptation/", "Analysis/32_behavior_exposure_adaptation.R", "registered post hoc evidence", "frozen", NA_character_, "Run v1.1_f4c7a31 (registry v1.0 with addendum A1); the aborted .tmp_v1.0_4f9c016 folder is kept read-only as evidence.", "manual",
    "33", "Post hoc cohort follow-ups (modules A-E)", NA_character_, "run-id output group", "analysis_ready/analyses/posthoc_cohort_followups/", "Analysis/33_posthoc_cohort_followups.R", "post hoc descriptive estimation (not registered)", "active_run_folders", NA_character_, "New run-id folders only; an existing folder is refused; frozen plan docs/STAGE33_POSTHOC_COHORT_FOLLOWUPS_PLAN_v1.0.md; no p-values reported (registered Stage 32 rows copied in module A only).", "manual",
    "config", "Frozen behavioural analysis configuration", NA_character_, "frozen record group", "analysis_ready/canonical/behavior_config/", "Analysis/_supporting/freeze_behavior_analysis_config.R", "frozen configuration record", "frozen", NA_character_, "Versions v1.0.0 and v1.0.1 (the configuration of the Stage 29 release).", "manual",
    "registry-29b", "Stage 29b registry (read-only copy)", NA_character_, "frozen record group", "analysis_ready/canonical/posthoc_con_contrasts_registry/", "docs/POSTHOC_CON_CONTRASTS_REGISTRY_v1.0.md", "registry", "frozen", NA_character_, "Read-only S: copy with its sha256 list; the Stage 29b runner gates on it.", "manual",
    "registry-30", "Stage 30 registry (read-only copy)", NA_character_, "frozen record group", "analysis_ready/canonical/stage30_registry/", "docs/stage30/", "registry", "frozen", NA_character_, "Read-only S: copy with FREEZE_RECORD.csv; the Stage 30 runner gates on it.", "manual",
    "registry-32", "Stage 32 registry and addendum A1 (read-only copies)", NA_character_, "frozen record group", "analysis_ready/canonical/stage32_registry/", "docs/STAGE32_REGISTRY_v1.0.md; docs/STAGE32_REGISTRY_v1.0_ADDENDUM_A1.md", "registry", "frozen", NA_character_, "Read-only S: copies with their sha256 lists; the Stage 32 runner gates on them.", "manual"
  )
  output_index$notes <- vapply(seq_len(nrow(output_index)), function(i) {
    legacy <- output_index$legacy_path[[i]]
    note <- output_index$notes[[i]]
    numbered <- if (is.na(legacy)) NA_character_ else
      sub("^analysis_ready/([^/]+)/.*$", "\\1", legacy)
    if (is.na(numbered) || !numbered %in% MMM_NUMBERED_BEHAVIOR_ROOTS) return(note)
    retained <- mmm_source_relative_path(
      mmm_behavior_numbered_source_root(numbered, base_dir), base_dir)
    if (identical(retained, numbered)) return(note)
    retained <- paste0(retained,
                       substring(legacy, nchar(paste0("analysis_ready/", numbered)) + 1L))
    if (!file.exists(file.path(base_dir, "analysis_ready", sub("/+$", "", retained)))) {
      return(note)
    }
    paste0(note, " Retained original: analysis_ready/", retained)
  }, character(1))
  if (anyDuplicated(stats::na.omit(output_index$canonical_path))) {
    stop("output_index.csv contains duplicate canonical paths.", call. = FALSE)
  }
  output_index
}
