# ================================================================
# Manuscript documentation writers (legends + publication README)
# MMMSociability
# ================================================================
# Text-only. Kept out of the assembly script so that prose edits never risk
# touching plotting or table logic.
# ================================================================

suppressPackageStartupMessages({ library(dplyr) })

#' Draft figure legends for the GAMM main and Extended Data candidates.
mmm_write_gamm_legends <- function(path, n_female = 58L, n_male = 53L) {
  n_txt <- paste0("n = ", n_female, " female and ", n_male,
                  " male animals (", n_female + n_male, " total).")
  l <- c(
"# GAMM figure legends (draft)",
"",
"Semantic filenames; manuscript figure numbers are assigned at whole-manuscript assembly.",
"Group colours are fixed: CON #3E3C6F, RES #C6C3BB, SUS #E63A48. Because RES is light, colour is",
"always redundant with line type (CON solid, RES long-dash, SUS dot-dash) and, in point summaries,",
"with shape (CON circle, RES triangle, SUS square).",
"",
"**Definitions used throughout.** *Active AUC*: trapezoidal integral of the fitted population",
"trajectory across the 12 h window, in log1p(Movement) x h. *Activity-bin probability*: the",
"probability that a scheduled 10-min Inactive-phase bin contains at least one RFID PositionID",
"transition. *Activity-probability AUC*: the integral of that probability across the 12 h Inactive",
"window, in probability-hours; dividing by 12 gives the expected fraction of active bins.",
"*ActiveBin* = 1 if Movement > 0, otherwise 0.",
"",
"---",
"",
"## first_active_trajectory_main",
"**Acute locomotor response during the first Active phase after the first cage change.**",
"a, Female. b, Male. Lines are fitted population trajectories; bands are 95% confidence intervals.",
"Curves are displayed on the inverse-transformed model scale. GAMMs were fitted to",
"log1p-transformed Movement with an AR1 residual term, batch adjustment and an animal random",
paste0("effect. ", n_txt),
"",
"## first_active_auc_contrasts_main",
"**Integrated first-night response does not separate later phenotype groups.**",
"Points are differences in window-integrated AUC with 95% confidence intervals; the vertical line",
"marks no difference. Statistics are Wald tests on the integrated contrast, Benjamini-Hochberg",
"corrected within a prespecified family of 2 sexes x 3 group contrasts = 6 tests. SUS-RES is the",
paste0("primary phenotype contrast; the other two are contextual controls. ", n_txt),
"",
"## active_auc_by_cagechange_main",
"**Acute locomotor response increases across successive cage changes.**",
"Points are fitted acute-response AUCs for each cage change with 95% confidence intervals, joined",
paste0("within group. a, Female. b, Male. ", n_txt),
"",
"## active_cc4_minus_cc1_main",
"**Adaptation from the first to the fourth cage change.**",
"Differences in acute-response AUC between CC4 and CC1 with 95% confidence intervals. The overall",
"row belongs to a 2-test family; the group rows belong to a separate 6-test localization family.",
"Phenotype-dependent difference-of-differences contrasts form a third, separate 6-test family and",
paste0("are reported in the tables rather than in this panel. ", n_txt),
"",
"## first_inactive_probability_main",
"**Locomotor activation during the first Inactive phase after the first cage change.**",
"Lines are marginal probabilities that a scheduled 10-min bin contains locomotor activity, derived",
"by running a fitted first-order state-dependent binomial GAMM forward from the scheduled start of",
"the phase; bands are 95% coefficient-simulation intervals. This is a measure of locomotor",
paste0("activation, not of sleep. ", n_txt),
"",
"## first_inactive_auc_contrasts_main",
"**Integrated inactive-phase activation differs between groups in males.**",
"Differences in the expected percentage of active 10-min bins with 95% confidence intervals.",
"Statistics are delta-method Wald tests on the integrated marginal-probability contrast,",
paste0("Benjamini-Hochberg corrected within a separate 6-test Inactive family. ", n_txt),
"",
"---",
"",
"## Extended Data",
"",
"**ED1** CC1 Active trajectories by Active night. **ED2** Active trajectories after each of the four",
"cage changes. **ED3** Pointwise predicted group-difference curves with 95% bands. **ED4** Stage 20",
"versus Stage 22 CC1 prediction audit, RMSE against the standalone first-night model. **ED5**",
"Confidence-interval width under batch, AR1 and covariance variants, relative to the primary model.",
"**ED6** CC1 Inactive activation probability by block. **ED7** Inactive activation probability after",
"each cage change. **ED8** Activation and persistence probabilities, the two transition components",
"of the marginal trajectory. **ED9** Calibration of the Inactive Markov model, observed against",
"predicted activity probability by decile.")
  writeLines(l, path)
  invisible(path)
}

#' Publication README for the Stage 26 tree.
mmm_write_gamm_readme <- function(path, colours, base_pt, label_pt,
                                  w_single, w_medium, w_double, h_max,
                                  n_female = 58L, n_male = 53L) {
  r <- c(
"# GAMM manuscript outputs (Stage 26)",
"",
"Assembly-only stage. It reads frozen Stage 20-25 outputs and never fits a model, recomputes a",
"p-value, or changes a multiplicity family. A co-author should be able to understand the whole",
"GAMM output tree from this file without reading R code.",
"",
"## Scientific role of the analysis stages",
"",
"| Stage | Phase | Estimand | Role |",
"|---|---|---|---|",
"| 20 | Active | acute response in the first Active block after CC1 (the Stage 09 window) | PRIMARY |",
"| 21 | Active | organization across all CC1 Active nights | secondary |",
"| 22 | Active | acute response after each of CC1-CC4 and adaptation across them | secondary |",
"| 23 | Inactive | activation probability in the first post-active Inactive block | secondary |",
"| 24 | Inactive | activation across the CC1 Inactive blocks | secondary |",
"| 25 | Inactive | activation after each of CC1-CC4 | secondary |",
"",
"Stage 20 is deliberately standalone: fitting CC2-CC4 jointly would let later observations",
"influence the CC1 curve through shared smooths, shared smoothing parameters and the model",
"covariance. Stage 22 exports a CC1 marginal only as a cross-model sensitivity (ED4).",
"",
"## Estimands",
"",
"Active stages model log1p(Movement) with an AR1 residual term, batch adjustment and an animal",
"random effect. Inactive stages model ActiveBin = 1 if Movement > 0 as a first-order",
"state-dependent binomial GAMM: serial dependence enters explicitly as PrevState in",
"{START, INACTIVE, ACTIVE} rather than as a residual AR1, because the dependence is part of the",
"biological process and bam AR1 is Gaussian-only. The manuscript Inactive quantity is the MARGINAL",
"probability obtained by running the fitted transition probabilities forward from the scheduled",
"start of the phase, never a conditional transition probability.",
"",
"## AUC definitions",
"",
"Active AUC is the trapezoidal integral of the fitted trajectory over the 12 h window, in",
"log1p(Movement) x h. Inactive activity-probability AUC is the integral of the marginal probability",
"over 12 h, in probability-hours; AUC/12 is the expected fraction of active bins and 100 x AUC/12",
"the expected percentage. AUC and AUC/12 are the same test in different units and are counted once.",
"",
"## Multiplicity families",
"",
"| Family | Tests | Question |",
"|---|---|---|",
"| PRIMARY_FIRST_ACTIVE | 6 | first-night group differences (Stage 20) |",
"| SECONDARY_FIRST_INACTIVE_MARKOV | 6 | first-Inactive group differences (Stage 23) |",
"| ADAPTATION A_OVERALL | 2 | is there adaptation at all |",
"| ADAPTATION B_GROUP_SPECIFIC | 6 | which groups show it |",
"| ADAPTATION C_PHENOTYPE_DEPENDENT | 6 | does adaptation differ between phenotypes |",
"| local per-stratum contrasts | 24 global | plus labelled within-Sex and within-stratum values |",
"",
"q_BH_all14_sensitivity is a CONSERVATIVE_SENSITIVITY column and never replaces a family q value.",
"Active and Inactive families are never combined. Cross-sex moderation is reported separately and",
"is never pooled into the adaptation families.",
"",
"## Descriptive versus inferential",
"",
"Descriptive only: animal-level empirical AUC, positive-count magnitude summaries, observed",
"transition frequencies and all diagnostics. Everything in the manuscript tables is inferential.",
"",
"## Retired analyses",
"",
"The earlier Gaussian log1p Inactive models are retired. They are preserved under each Inactive",
"stage audit/gaussian_log1p_invalid/ directory with the status MODEL_INADEQUATE__DO_NOT_INTERPRET",
"and must not be cited. Stage 26 refuses to read any table carrying that status.",
"",
"## Presentation specification",
"",
paste0("Group colours are fixed: CON ", colours[["CON"]], ", RES ", colours[["RES"]],
       ", SUS ", colours[["SUS"]], ". Colour is always redundant with line type (CON solid,"),
"RES long-dash, SUS dot-dash) and with point shape (CON circle, RES triangle, SUS square), so the",
"figures remain readable in greyscale and for colour-vision-deficient readers.",
paste0("Body text ", base_pt, " pt; panel labels ", label_pt,
       " pt bold lowercase; sans (Helvetica/Arial)."),
paste0("Widths: single ", w_single, " mm, medium ", w_medium, " mm, double ", w_double,
       " mm. Maximum height ", h_max, " mm."),
"Every main and Extended Data figure is exported as editable-text PDF and SVG with a PNG preview.",
"White background, no gridlines, no panel borders, no grey strip backgrounds, RGB colour.",
"",
"## Source Data",
"",
"source_data/ holds one table per plotted panel plus source_data_manifest.csv, mapping figure file",
"to panel to source table to analysis table to model id to producing script.",
"",
"## Reporting n",
"",
paste0("Figures and tables report n animals (", n_female, " female, ", n_male,
       " male). Bin counts are model"),
"diagnostics and appear only in Extended Data and Methods; 10-min bins are not independent",
"replicates and are never presented as such.")
  writeLines(r, path)
  invisible(path)
}
